const axios = require('axios');
const PDFDocument = require('pdfkit');

/**
 * Cover Letter Service
 * Generates cover letters via LLM with tone-specific prompts.
 * Supports SSE streaming and PDF generation.
 */

const TONE_INSTRUCTIONS = {
    formal: `Write in a formal, polished, third-person-aware tone. Use complete sentences, avoid contractions, and maintain professional distance. Structure: Opening paragraph (interest + role), Middle paragraph (top 2 relevant achievements), Closing paragraph (call to action).`,
    confident: `Write in a direct, first-person, assertive tone. Lead with impact. Use phrases like "I will", "I bring", "My record shows". Avoid hedging language. Structure: Hook sentence, Achievement paragraph, Why this company paragraph, CTA.`,
    concise: `Write a concise cover letter under 200 words. No filler sentences. Every sentence must add unique value. Bullet-point format for achievements is acceptable. Structure: 1-sentence intro, 3 bullet achievements, 1-sentence close.`
};

/**
 * Build the LLM prompt for cover letter generation.
 */
function buildPrompt(resumeText, jobDescription, companyName, jobTitle, tone, personalNotes) {
    const toneInstruction = TONE_INSTRUCTIONS[tone] || TONE_INSTRUCTIONS.formal;

    return `You are a professional career coach and expert writer crafting a cover letter.

CANDIDATE RESUME:
${resumeText}

JOB DESCRIPTION:
${jobDescription}

COMPANY: ${companyName || 'the hiring company'}
ROLE: ${jobTitle || 'the advertised position'}
PERSONAL NOTES FROM CANDIDATE: ${personalNotes || 'None provided'}

TONE INSTRUCTION:
${toneInstruction}

RULES:
- Reference specific skills and keywords from the JD organically.
- Do NOT fabricate companies or dates not present in the resume.
- Do NOT include placeholder text like [Your Name] — infer from resume if available, else omit.
- Output only the cover letter body. No subject line. No JSON wrapper.`;
}

/**
 * Generate cover letter via streaming LLM call.
 * Returns the axios response for streaming.
 * @returns {Object} Axios response with data stream
 */
async function generateCoverLetterStream(resumeText, jobDescription, companyName, jobTitle, tone, personalNotes) {
    const prompt = buildPrompt(resumeText, jobDescription, companyName, jobTitle, tone, personalNotes);

    const response = await axios.post(
        'https://openrouter.ai/api/v1/chat/completions',
        {
            model: 'meta-llama/llama-3.3-70b-instruct',
            messages: [
                { role: 'system', content: 'You are an expert cover letter writer. Write only the cover letter body.' },
                { role: 'user', content: prompt }
            ],
            temperature: 0.6,
            stream: true
        },
        {
            headers: {
                'Authorization': `Bearer ${process.env.OPENROUTER_API_KEY}`,
                'HTTP-Referer': process.env.APP_URL || 'http://localhost:5000',
                'X-Title': 'Resume Analyzer'
            },
            responseType: 'stream'
        }
    );

    return response;
}

/**
 * Generate a cover letter PDF using PDFKit.
 * @param {string} text - The cover letter text
 * @param {Object} metadata - { companyName, jobTitle, tone }
 * @returns {PDFDocument} Pipeable PDF stream
 */
function generateCoverLetterPDF(text, metadata = {}) {
    const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 60, bottom: 60, left: 60, right: 60 },
        info: {
            Title: `Cover Letter - ${metadata.jobTitle || 'Application'}`,
            Author: 'JDFit',
            Subject: 'Cover Letter'
        }
    });

    // Header
    doc.fontSize(10)
        .fillColor('#6B7280')
        .text(new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }), { align: 'right' });

    doc.moveDown(2);

    if (metadata.companyName) {
        doc.fontSize(11)
            .fillColor('#374151')
            .text(metadata.companyName);
    }

    if (metadata.jobTitle) {
        doc.fontSize(11)
            .fillColor('#374151')
            .text(`Re: ${metadata.jobTitle}`);
    }

    doc.moveDown(1.5);

    // Body
    doc.fontSize(11)
        .fillColor('#111827')
        .text(text, {
            lineGap: 4,
            paragraphGap: 8,
            align: 'left'
        });

    // Footer
    doc.moveDown(3);
    doc.fontSize(8)
        .fillColor('#9CA3AF')
        .text('Generated by JDFit — AI-powered resume analysis', { align: 'center' });

    doc.end();
    return doc;
}

module.exports = { generateCoverLetterStream, generateCoverLetterPDF, buildPrompt };
